const books = [
  {
    name: "Great",
    isCut: true,
    category: "Novel",
    rating: 3.1,
    number: 2,
    from: "1970.01",
    to: "1981.04",
  },
  {
    name: "Laws",
    isCut: true,
    category: "Novel",
    rating: 4.8,
    number: 3,
    from: "1980.06",
    to: "1985.07",
  },
  {
    name: "Dracula",
    isCut: true,
    category: "Drama",
    rating: 2.3,
    number: 6,
    from: "1991.05",
    to: "1996.05",
  },
  {
    name: "Mario",
    isCut: true,
    category: "Drama",
    rating: 3.8,
    number: 4,
    from: "2001.09",
    to: "2012.11",
  },
  {
    name: "House",
    isCut: false,
    category: "Magazine",
    rating: 4.4,
    number: 1,
    from: "1987.07",
    to: "",
  },
  {
    name: "Art1",
    isCut: true,
    category: "Design",
    rating: 4.2,
    number: 2,
    from: "1985.06",
    to: "1991.07",
  },
  {
    name: "Art2",
    isCut: true,
    category: "Design",
    rating: 3.0,
    number: 3,
    from: "1995.02",
    to: "2005.12",
  },
  {
    name: "Wars",
    isCut: true,
    category: "Novel",
    rating: 4.6,
    number: 2,
    from: "1982.04",
    to: "2003.05",
  },
  {
    name: "Solo",
    isCut: false,
    category: "Poem",
    rating: 4.9,
    number: 2,
    from: "2007.03",
    to: "",
  },
  {
    name: "Lost",
    isCut: false,
    category: "Web",
    rating: 3.2,
    number: 8,
    from: "1998.06",
    to: "",
  },
  {
    name: "Ocean",
    isCut: true,
    category: "Magazine",
    rating: 4.3,
    number: 1,
    from: "2005.02",
    to: "2020.06",
  },
];

export default books;
