const books = [
  {
    name: "Great",
    isOutOfPrint: true,
    category: "Novel",
    rating: 3.1,
    number: 2,
    from: new Date("1970.01"),
    to: new Date("1981.04"),
  },
  {
    name: "Laws",
    isOutOfPrint: true,
    category: "Novel",
    rating: 4.8,
    number: 3,
    from: new Date("1980.06"),
    to: new Date("1985.07"),
  },
  {
    name: "Dracula",
    isOutOfPrint: true,
    category: "Drama",
    rating: 2.3,
    number: 6,
    from: new Date("1991.05"),
    to: new Date("1996.05"),
  },
  {
    name: "Mario",
    isOutOfPrint: true,
    category: "Drama",
    rating: 3.8,
    number: 4,
    from: new Date("2001.09"),
    to: new Date("2012.11"),
  },
  {
    name: "House",
    isOutOfPrint: false,
    category: "Magazine",
    rating: 4.4,
    number: 1,
    from: new Date("1987.07"),
    to: new Date(),
  },
  {
    name: "Art1",
    isOutOfPrint: true,
    category: "Design",
    rating: 4.2,
    number: 2,
    from: new Date("1985.06"),
    to: new Date("1991.07"),
  },
  {
    name: "Art2",
    isOutOfPrint: true,
    category: "Design",
    rating: 3.0,
    number: 3,
    from: new Date("1995.02"),
    to: new Date("2005.12"),
  },
  {
    name: "Wars",
    isOutOfPrint: true,
    category: "Novel",
    rating: 4.6,
    number: 2,
    from: new Date("1982.04"),
    to: new Date("2003.05"),
  },
  {
    name: "Solo",
    isOutOfPrint: false,
    category: "Poem",
    rating: 4.9,
    number: 2,
    from: new Date("2007.03"),
    to: new Date(),
  },
  {
    name: "Lost",
    isOutOfPrint: false,
    category: "Web",
    rating: 3.2,
    number: 8,
    from: new Date("1998.06"),
    to: new Date(),
  },
  {
    name: "Ocean",
    isOutOfPrint: true,
    category: "Magazine",
    rating: 4.3,
    number: 1,
    from: new Date("2005.02"),
    to: new Date("2020.06"),
  },
];

export default books;
